### ISSUE TITLE
upload_max_filesize does not obey the max_length setting for the file field

### ISSUE THREAD

**Issue by teewuane** [devinemke/submgr#16]
If you try and change the `max_length` on the file field, it will not allow you to have larger uploads. It seems that the `upload_max_filesize` is fixed at 2mb. However if you click on the link it will set the `max_length` on the file field.

So I guess the question is, can I increase the upload_max_filesize? And if so, how do I do this?

A lot of people's documents are much larger than the current 2mb limit.

Thanks!

**Comment by teewuane** [comment]
A screen shot of the are I'm referring to.

If you click on `2097152`, it will set the value in the max_length for the file field to 2097152, which makes me believe the two are related.

How can I increase the max file upload to 10mb. I have already made the adjustment on nginx to allow for larger files.

<img width="709" alt="Screenshot 2024-03-19 at 9 55 40 PM" src="https://github.com/devinemke/submgr/assets/535433/21187f42-1c8d-4b6f-9fd1-4c5b51aa6b2d">

**Comment by devinemke** [comment]
@teewuane In SM **/configuration/fields/** you can specify the maximum file size that your SM will accept. However your PHP configuration has its own `upload_max_filesize` (usually set in **php.ini**) which supersedes the SM settings (and SM has no control over). That link on the lower right of your screenshot displays the current PHP `upload_max_filesize` and clicking it will auto-fill **/file/maxlength/** (thus allowing your SM to accept the largest file size that your server will allow).

So if you wish to accept files larger than **2MB** (you mentioned needing a **10MB** limit?) then your screenshot suggests that you need to alter your PHP `upload_max_filesize`.

Have you already done this? You mentioned having already tweaked your Nginx settings? If so then perhaps you need to restart the server if your PHP settings are not updating (assuming PHP is running as Server Handler API rather than as a CGI process).

Please advise. Thanks. -DE

**Comment by teewuane** [comment]
Thank you! This solved the issue for me. As you can probably tell PHP isn't my strength!

**Comment by teewuane** [comment]
Thank you! This solved the issue for me. As you can probably tell PHP isn't my strength!
